# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/pde/5_fdm_solver.ipynb (unless otherwise specified).

__all__ = ['AutogradLinearSolver', 'LinearSolver', 'SparseLinearSolver', 'PDESolver', 'FDMDerivatives',
           'FDMAdjointDerivatives', 'FDMAssembly', 'UnpaddedFDM', 'FDM']

# Cell
import torch
import numpy as np
import time
import importlib.util
import warnings
from scipy.sparse.linalg import factorized, use_solver, spsolve
from scipy.sparse import csc_matrix
from typing import Callable
import pyamg

try:
    use_solver(useUmfpack=True, assumeSortedIndices=True)
except Exception as e:
    warnings.warn(f"Not using UMFPACK: {e}")
    use_solver(useUmfpack=False, assumeSortedIndices=True)

# Internal Cell

from .utils import get_σ_vm
# from .pde import SparseLinearSolver, PDESolver, FDMDerivatives, FDMAdjointDerivatives, FDMAssembly, UnpaddedFDM
try:
    import cupy as cp
    from cupyx.scipy.sparse import csc_matrix as cp_csc_matrix
    from cupyx.scipy.sparse.linalg import spsolve as cp_spsolve
    from cupyx.scipy.sparse.linalg import cg as cg_spsolve
    from cupyx.scipy.sparse.linalg import LinearOperator
except ImportError:
    print("cupy is imported/used only if availabe ")
    cp = None
    
# Cell
class AutogradLinearSolver(torch.autograd.Function):
    @staticmethod
    def forward(ctx, θ, A_op, b, solver, A_mat, factorize=True):
        """
        In the forward pass we receive a tensor containing the input and return
        a tensor containing the output. `ctx` is a context object that can be used
        to stash information for backward computation. You can cache arbitrary
        objects for use in the backward pass using the `ctx.save_for_backward` method.

        Returns
        torch.Tensor
        """
        np_b = b.cpu().numpy()
        # Explicit phase label
        phase = 'forward'

        if factorize:
            solver = factorized(A_mat)
            x = solver(np_b)
        else:
            # pass phase explicitly and include θ for warm-start gating if solver supports it
            try:
                x = solver(A_mat, np_b, phase=phase, θ_current=θ.detach().cpu().numpy())
            except TypeError:
                # Backward compatibility if older signature
                x = solver(A_mat, np_b, phase=phase)

        x = torch.from_numpy(x.astype(np_b.dtype))
        ctx.save_for_backward(θ, x, b)
        ctx.intermediate = (A_mat, solver, A_op, factorize)
        return x


    @staticmethod
    def backward(ctx, grad_output):
        """
        In the backward pass we receive a tensor containing the gradient of the loss
        with respect to the output, and we need to compute the gradient of the loss
        with respect to the input.

        Returns
        ----------
        (torch.Tensor, None, None, None, None, None)
        """
        torch.set_grad_enabled(True)
        θ, x, b = ctx.saved_tensors
        A_mat, solver, A_op, factorize = ctx.intermediate
        θ = θ.clone().detach()
        θ.requires_grad_(True)

        with torch.no_grad():
            phase = 'adjoint'
            flat_np_grad_output = grad_output.flatten().cpu().numpy()

            if factorize:
                y = solver(flat_np_grad_output)
            else:
                try:
                    y = solver(A_mat, flat_np_grad_output, phase=phase, θ_current=θ.detach().cpu().numpy())
                except TypeError:
                    y = solver(A_mat, flat_np_grad_output, phase=phase)

            y = torch.from_numpy(y).clone().requires_grad_(False)
            x = x.clone().requires_grad_(False)

        expr = torch.sum(y * (b - A_op(x, θ).flatten()))
        grad_input = torch.autograd.grad(expr, θ)
        return grad_input[0], None, None, None, None, None

# Cell
class LinearSolver():
    """
    A parent class for linear solvers that are used to solve the linear system that solves the PDE.
    We compute the gradients via `torch.autograd` and with the adjoint method in the backwards pass.
    """
    def __init__(self,
                 factorize:bool=True # Whether the system matrix should be factorized.
                ):
        self.autograd_linear_solver = AutogradLinearSolver.apply
        self.factorize = factorize


    def _solver(self):
        raise NotImplementedError("Solver must be overridden.")


    def __call__(self,
                 θ:torch.Tensor, # The density for which the PDE is solved.
                 A_op:Callable[[torch.Tensor, torch.Tensor], torch.Tensor], # A function that takes `u` and `θ` as input and outputs the right hand side of the PDE. In other words, this is an operator representing the system matrix.
                 b:torch.Tensor, # A flattened version of the right side of the PDE.
                 A_mat:csc_matrix # The system matrix in sparse format.
                ):
        """
        Solves the PDE for the density `θ`. Returns the solution as a `torch.Tensor` object.
        """
        x = self.autograd_linear_solver(θ, A_op, b, self._solver(), A_mat, self.factorize)
        return x

# Cell
class SparseLinearSolver(LinearSolver):
    """
    A sparse linear solver that uses scipy (CPU) and optionally cupy (GPU) if available.
    """
    def __init__(self,
                 use_umfpack: bool = True,
                 factorize: bool = False,
                 use_cupy: bool = True,
                 cg_tol: float = 1e-6,
                 cg_max_iter: int = None,
                 cg_verbose: bool = True,
                 warm_start: bool = True,
                 warm_similarity_threshold: float = 0.9,  # RHS cosine similarity threshold (legacy)
                 warm_theta_tol: float = 1e-3,            # Absolute mean(θ) change tolerance for warm reuse
                 warm_strategy: str = 'theta',            # 'theta' | 'rhs' | 'both'
                 preconditioner: str = 'block_jacobi',    # 'none' | 'jacobi' | 'block_jacobi' | 'amg'
                 amg_smooth_steps: int = 4,               # GPU approx AMG: base Jacobi smoothing iterations
                 amg_omega: float = 0.75,                 # GPU approx AMG: damping factor
                 amg_adaptive: bool = True,               # Adapt smoothing based on previous CG iterations
                 amg_min_smooth_steps: int = 1            # Minimum smoothing steps when adapting
                 ):
        # Basic config
        self.use_umfpack = use_umfpack
        self.use_cupy_requested = use_cupy
        self.have_cupy = False
        self.backend = "scipy"
        self.cg_tol = cg_tol
        self.cg_max_iter = cg_max_iter
        self.cg_verbose = cg_verbose
        self.warm_start = warm_start
        self.warm_similarity_threshold = warm_similarity_threshold
        self.warm_theta_tol = warm_theta_tol
        self.warm_strategy = warm_strategy.lower()
        if self.warm_strategy not in ['theta', 'rhs', 'both']:
            raise ValueError("warm_strategy must be one of 'theta', 'rhs', 'both'")
        self.preconditioner = preconditioner.lower()
        if self.preconditioner not in ['none', 'jacobi', 'block_jacobi', 'amg']:
            raise ValueError("preconditioner must be 'none', 'jacobi', 'block_jacobi', or 'amg'")

        # AMG cache (CPU pattern reuse)
        self._amg_hierarchy = None
        self._amg_key = None
        # GPU approximate AMG cached components & parameters
        self._amg_diag_inv = None
        self._last_cg_iters = None
        self.amg_smooth_steps = amg_smooth_steps
        self.amg_omega = amg_omega
        self.amg_adaptive = amg_adaptive
        self.amg_min_smooth_steps = amg_min_smooth_steps
        # Block-Jacobi cache config
        self.bj_cache = True
        self.bj_theta_tol = 1e-3
        self.bj_rebuild_every = 0  # 0 disables periodic rebuild
        # Cached state for block-jacobi (interleaved)
        self._bj_cache = {
            'key': None,             # pattern key
            'offsets': None,         # cp.ndarray (N,3,3) absolute indices into csr.data (-1 if missing)
            'inv_blocks': None,      # cp.ndarray (N,3,3)
            'operator': None,        # LinearOperator capturing inv_blocks reference
            'theta_prev': None,      # cp.ndarray (N,)
            'N': 0,                  # number of nodes
            'build_count': 0         # times rebuilt fully
        }
        # Auto-freeze/unfreeze controls for BJ updates
        self.bj_freeze_enabled = True
        self.bj_freeze_patience = 3          # consecutive small-Δθ steps to freeze
        self.bj_freeze_theta_tol = 1e-4      # mean(θ) change threshold to count as "stable"
        self.bj_unfreeze_iter_jump = 1.5     # if CG iters jump by this factor vs baseline, unfreeze
        self._bj_freeze_state = {
            'frozen': False,
            'stable_steps': 0,
            'prev_mean': None,
            'baseline_iters': None,
            'step': 0
        }
        # Partial update controls
        self.bj_update_fraction = 0.2       # update at most 20% nodes per refresh
        self.bj_min_update = 4096           # but at least this many nodes
        self.bj_update_period = 1           # perform value update every k solves (1 = every time)
        self.bj_partitions = 1              # round-robin partitions (1 = disabled)

        # GPU structural cache
        self._gpu_shape = None
        self._gpu_indices = None
        self._gpu_indptr = None

        # Phase separated warm caches: {'forward': {'x': cp.array, 'b': cp.array}, 'adjoint': {...}}
        self._warm_cache = {
            'forward': {'x': None, 'b': None, 'θ': None},
            'adjoint': {'x': None, 'b': None, 'θ': None}
        }

        # Cupy availability
        if use_cupy:
            try:
                import cupy  # noqa: F401
                if torch.cuda.is_available():
                    self.have_cupy = True
                    self.backend = "cupy"
                else:
                    warnings.warn("CUDA not available; falling back to scipy backend.")
            except ImportError:
                warnings.warn("cupy not installed; falling back to scipy backend.")

        # Factorization only for CPU
        if self.have_cupy and factorize:
            warnings.warn("Factorization not supported with cupy backend. Disabling factorization.")
            factorize = False

        # If GPU: we'll implement a lightweight approximate AMG (multi-step Jacobi inverse) directly
        if self.preconditioner == 'amg' and self.have_cupy:
            if self.cg_verbose:
                print("[amg] GPU approximate AMG enabled (multi-step Jacobi smoother).")

        if self.preconditioner == 'amg' and factorize:
            warnings.warn("AMG conflicts with direct factorization; switching to iterative (factorize=False).")
            self.factorize = False

        if (use_umfpack or factorize) and (importlib.util.find_spec('scikits') is None) and (self.backend == "scipy"):
            warnings.warn("scikits.umfpack not installed. Falling back to default scipy solver.")

        super().__init__(factorize)

    # def _solver(self):
    #     def amg_solver(A, b):
    #         # key = A.shape + (A.nnz,)
    #         # if key not in self.ml_cache:
    #         #     print("[pyamg] Building new AMG hierarchy for matrix shape", A.shape)
    #         #     self.ml_cache[key] = pyamg.smoothed_aggregation_solver(A)
    #         # ml = self.ml_cache[key]
    #         ml = pyamg.smoothed_aggregation_solver(A.tocsr())
            
    #         x = ml.solve(b, tol=1e-10, accel='cg')
    #         return x
    #     return amg_solver

    def _solver(self):
        if self.have_cupy:
            # GPU solver
            def solve_gpu(A, b, phase='forward', θ_current=None):
                # (1) Upload / reuse sparsity pattern
                # Reuse indices/indptr if shape unchanged to avoid repeated allocations
                if (self._gpu_shape != A.shape) or (self._gpu_indices is None) or (self._gpu_indptr is None):
                    # Rebuild sparsity pattern if:
                    # - shape changed
                    # - first time (_gpu_indices/_gpu_indptr None)
                    # - nnz changed (e.g. different Dirichlet mask or structural modification)
                    if (self._gpu_shape != A.shape) or \
                       (self._gpu_indices is None) or \
                       (self._gpu_indptr is None) or \
                       (getattr(self, "_gpu_nnz", None) != A.nnz):
                        self._gpu_shape = A.shape
                        self._gpu_indices = cp.asarray(A.indices)
                        self._gpu_indptr = cp.asarray(A.indptr)
                        self._gpu_nnz = A.nnz
                # Always upload fresh numeric values (data changes each call)
                data_gpu = cp.asarray(A.data)
                A_gpu = cp_csc_matrix((data_gpu, self._gpu_indices, self._gpu_indptr), shape=A.shape)

                # (2) Build / select preconditioner
                M = None
                if self.preconditioner == 'none':
                    M = None
                elif self.preconditioner == 'jacobi':
                    diag = A_gpu.diagonal()
                    inv_diag = cp.where(diag != 0, 1.0 / diag, 1.0)
                    def mv(x):
                        return inv_diag * x
                    M = LinearOperator(A_gpu.shape, matvec=mv, dtype=A_gpu.dtype)
                elif self.preconditioner == 'block_jacobi':
                        def create_block_jacobi_preconditioner_interleaved_vectorized(A_gpu, theta_vec=None):
                            n_dofs = A_gpu.shape[0]
                            if n_dofs % 3 != 0:
                                diag = A_gpu.diagonal()
                                inv_diag = cp.where(cp.abs(diag) > 1e-12, 1.0 / diag, 0.0)
                                def mv(x):
                                    return inv_diag * x
                                return LinearOperator(A_gpu.shape, matvec=mv, dtype=A_gpu.dtype)

                            N = n_dofs // 3
                            # Pattern key using cheap hashes on indices/indptr
                            csr = A_gpu.tocsr()
                            try:
                                key = (A_gpu.shape,
                                       int(A_gpu.nnz),
                                       int(csr.indptr.size), int(csr.indices.size),
                                       int(cp.sum(csr.indptr.astype(cp.int64)).get()),
                                       int(cp.sum(csr.indices.astype(cp.int64)).get()))
                            except Exception:
                                key = (A_gpu.shape, int(A_gpu.nnz))

                            cache = self._bj_cache
                            new_pattern = (not self.bj_cache) or (cache['key'] != key) or (cache['N'] != N)
                            do_full_rebuild = new_pattern
                            # Optional periodic full rebuild
                            if (not do_full_rebuild) and (self.bj_rebuild_every and (cache['build_count'] % self.bj_rebuild_every == 0)):
                                do_full_rebuild = True

                            if do_full_rebuild:
                                # Build offsets and full blocks
                                if self.cg_verbose:
                                    print(f"[cupy][cg][block_jacobi] full build N={N} nnz={A_gpu.nnz}")
                                t0 = time.time()
                                offsets = cp.full((N,3,3), -1, dtype=cp.int64)
                                blocks = cp.zeros((N, 3, 3), dtype=A_gpu.dtype)
                                for i_node in range(N):
                                    base_row = 3 * i_node
                                    for r in range(3):
                                        row_idx = base_row + r
                                        rs = csr.indptr[row_idx]; re = csr.indptr[row_idx + 1]
                                        cols = csr.indices[rs:re]
                                        # For each target column position
                                        for c in range(3):
                                            col_idx = base_row + c
                                            pos = cp.where(cols == col_idx)[0]
                                            if pos.size > 0:
                                                offsets[i_node, r, c] = rs + pos[0].astype(cp.int64)
                                # Gather block values using offsets
                                data_arr = csr.data
                                for r in range(3):
                                    for c in range(3):
                                        off = offsets[:, r, c]
                                        mask = off >= 0
                                        vals = cp.zeros(N, dtype=A_gpu.dtype)
                                        if mask.any():
                                            vals[mask] = data_arr[off[mask]]
                                        blocks[:, r, c] = vals
                                cache['offsets'] = offsets
                                cache['key'] = key
                                cache['N'] = N
                                cache['build_count'] += 1
                                if self.cg_verbose:
                                    print(f"[cupy][cg][block_jacobi] offsets built in {time.time()-t0:.3f}s")
                            else:
                                # Reuse offsets and selectively update changed nodes
                                offsets = cache['offsets']
                                # If frozen, skip all value updates and reuse existing inv_blocks
                                if self.bj_freeze_enabled and self._bj_freeze_state.get('frozen', False):
                                    if self.cg_verbose:
                                        print("[cupy][cg][block_jacobi] frozen: skipping value update")
                                    # Ensure inv_blocks exists
                                    if cache.get('inv_blocks') is None:
                                        raise RuntimeError("Block-Jacobi frozen without existing inv_blocks; this should not happen.")
                                    # Short-circuit to matvec creation using existing inv_blocks
                                    blocks = None  # signal no-recompute
                                else:
                                    # Respect update period
                                    if (self.bj_update_period > 1) and (self._bj_freeze_state.get('step', 0) % self.bj_update_period != 0):
                                        if self.cg_verbose:
                                            print(f"[cupy][cg][block_jacobi] skip update (period={self.bj_update_period})")
                                        blocks = None
                                    else:
                                        # Compute changed set and optionally throttle updates
                                        data_arr = csr.data
                                        # If theta available, update only changed nodes, else all
                                        if theta_vec is not None and cache.get('theta_prev') is not None and theta_vec.size == cache['theta_prev'].size:
                                            dθ = cp.abs(theta_vec - cache['theta_prev'])
                                            changed = (dθ > self.bj_theta_tol)
                                        else:
                                            dθ = None
                                            changed = cp.ones(N, dtype=cp.bool_)
                                        # Round-robin partitioning if enabled
                                        part_mask = cp.ones(N, dtype=cp.bool_)
                                        if self.bj_partitions and self.bj_partitions > 1:
                                            step = int(self._bj_freeze_state.get('step', 0))
                                            part = step % self.bj_partitions
                                            # Nodes assigned by modulo on index
                                            idx_all = cp.arange(N)
                                            part_mask = (idx_all % self.bj_partitions) == part
                                        candidates = changed & part_mask
                                        idx = cp.where(candidates)[0]
                                        if idx.size == 0:
                                            blocks = None
                                        else:
                                            # Throttle update count
                                            if self.bj_update_fraction < 1.0:
                                                max_update = int(max(self.bj_min_update, self.bj_update_fraction * N / max(1, self.bj_partitions)))
                                                if idx.size > max_update:
                                                    if dθ is not None:
                                                        # pick top-k by dθ among candidates
                                                        dθ_cand = dθ[idx]
                                                        k = max_update
                                                        # argpartition for top-k indices
                                                        sel = cp.argpartition(-dθ_cand, k-1)[:k]
                                                        idx = idx[sel]
                                                    else:
                                                        # no dθ available, take first k
                                                        idx = idx[:max_update]
                                            # Gather values for selected nodes
                                            blocks = cp.zeros((N, 3, 3), dtype=A_gpu.dtype)
                                            for r in range(3):
                                                for c in range(3):
                                                    off = offsets[idx, r, c]
                                                    mask = off >= 0
                                                    vals = cp.zeros(idx.size, dtype=A_gpu.dtype)
                                                    if mask.any():
                                                        vals[mask] = data_arr[off[mask]]
                                                    blocks[idx, r, c] = vals
                                    blocks = cp.zeros((N, 3, 3), dtype=A_gpu.dtype)
                                    data_arr = csr.data
                                    # If theta available, update only changed nodes, else all
                                    if theta_vec is not None and cache.get('theta_prev') is not None and theta_vec.size == cache['theta_prev'].size:
                                        dθ = cp.abs(theta_vec - cache['theta_prev'])
                                        changed = (dθ > self.bj_theta_tol)
                                    else:
                                        changed = cp.ones(N, dtype=cp.bool_)
                                    # Gather values for changed nodes
                                    idx = cp.where(changed)[0]
                                    if idx.size > 0:
                                        for r in range(3):
                                            for c in range(3):
                                                off = offsets[idx, r, c]
                                                mask = off >= 0
                                                vals = cp.zeros(idx.size, dtype=A_gpu.dtype)
                                                if mask.any():
                                                    vals[mask] = data_arr[off[mask]]
                                                blocks[idx, r, c] = vals
                                    # For unchanged nodes, keep previous inv_blocks (no need to fill blocks)

                            if blocks is not None:
                                a = blocks[:, 0, 0]; b = blocks[:, 0, 1]; c_ = blocks[:, 0, 2]
                                d = blocks[:, 1, 0]; e = blocks[:, 1, 1]; f = blocks[:, 1, 2]
                                g = blocks[:, 2, 0]; h = blocks[:, 2, 1]; i_ = blocks[:, 2, 2]
                                det = (a * (e * i_ - f * h) - b * (d * i_ - f * g) + c_ * (d * h - e * g))
                                det_safe = cp.where(cp.abs(det) > 1e-12, det, cp.sign(det) * 1e-12)
                                if self.cg_verbose and (do_full_rebuild or (idx.size if 'idx' in locals() else N) == N):
                                    det_abs = cp.abs(det)
                                    det_min = float(det_abs.min().get()) if det_abs.size else 0.0
                                    det_max = float(det_abs.max().get()) if det_abs.size else 0.0
                                    det_mean = float(det_abs.mean().get()) if det_abs.size else 0.0
                                    near = int((det_abs < 1e-12).sum().get())
                                    print(f"[cupy][cg][block_jacobi] det stats |min|={det_min:.3e} |max|={det_max:.3e} |mean|={det_mean:.3e} near_sing={near}")

                            # Initialize or update inverse blocks
                            if blocks is None:
                                inv_blocks = cache['inv_blocks']
                            elif do_full_rebuild or cache.get('inv_blocks') is None:
                                inv_blocks = cp.zeros((N, 3, 3), dtype=A_gpu.dtype)
                                inv_blocks[:, 0, 0] = (e * i_ - f * h) / det_safe
                                inv_blocks[:, 0, 1] = (c_ * h - b * i_) / det_safe
                                inv_blocks[:, 0, 2] = (b * f - c_ * e) / det_safe
                                inv_blocks[:, 1, 0] = (f * g - d * i_) / det_safe
                                inv_blocks[:, 1, 1] = (a * i_ - c_ * g) / det_safe
                                inv_blocks[:, 1, 2] = (c_ * d - a * f) / det_safe
                                inv_blocks[:, 2, 0] = (d * h - e * g) / det_safe
                                inv_blocks[:, 2, 1] = (b * g - a * h) / det_safe
                                inv_blocks[:, 2, 2] = (a * e - b * d) / det_safe
                                cache['inv_blocks'] = inv_blocks
                            else:
                                inv_blocks = cache['inv_blocks']
                                if 'idx' in locals() and idx.size > 0:
                                    # Recompute only changed rows for idx
                                    inv_blocks[idx, 0, 0] = (e[idx] * i_[idx] - f[idx] * h[idx]) / det_safe[idx]
                                    inv_blocks[idx, 0, 1] = (c_[idx] * h[idx] - b[idx] * i_[idx]) / det_safe[idx]
                                    inv_blocks[idx, 0, 2] = (b[idx] * f[idx] - c_[idx] * e[idx]) / det_safe[idx]
                                    inv_blocks[idx, 1, 0] = (f[idx] * g[idx] - d[idx] * i_[idx]) / det_safe[idx]
                                    inv_blocks[idx, 1, 1] = (a[idx] * i_[idx] - c_[idx] * g[idx]) / det_safe[idx]
                                    inv_blocks[idx, 1, 2] = (c_[idx] * d[idx] - a[idx] * f[idx]) / det_safe[idx]
                                    inv_blocks[idx, 2, 0] = (d[idx] * h[idx] - e[idx] * g[idx]) / det_safe[idx]
                                    inv_blocks[idx, 2, 1] = (b[idx] * g[idx] - a[idx] * h[idx]) / det_safe[idx]
                                    inv_blocks[idx, 2, 2] = (a[idx] * e[idx] - b[idx] * d[idx]) / det_safe[idx]

                            def mv(x):
                                x_mat = x.reshape((N, 3))
                                res = cp.zeros_like(x_mat)
                                # Use cached inv_blocks in-place
                                for rr in range(3):
                                    for cc in range(3):
                                        res[:, rr] += inv_blocks[:, rr, cc] * x_mat[:, cc]
                                return res.reshape(n_dofs)

                            # Update cached theta only when we recomputed values (full build or partial idx update)
                            if theta_vec is not None and (do_full_rebuild or (blocks is not None and ('idx' in locals() and idx.size > 0))):
                                cache['theta_prev'] = theta_vec.copy() if isinstance(theta_vec, cp.ndarray) else cp.asarray(theta_vec)

                            # Create operator once and reuse; else return existing
                            if cache.get('operator') is None or do_full_rebuild:
                                if self.cg_verbose:
                                    print("[cupy][cg][block_jacobi] operator (re)created")
                                op = LinearOperator(A_gpu.shape, matvec=mv, dtype=A_gpu.dtype)
                                cache['operator'] = op
                            return cache['operator']

                        theta_vec = None
                        if θ_current is not None:
                            try:
                                theta_vec = cp.asarray(θ_current, dtype=cp.float32).ravel()
                            except Exception:
                                theta_vec = None
                        M = create_block_jacobi_preconditioner_interleaved_vectorized(A_gpu, theta_vec)
                        if self.cg_verbose:
                            print(f"[cupy][cg] block_jacobi (interleaved) built (N={A_gpu.shape[0]//3})")
                elif self.preconditioner == 'amg':
                    # Lightweight approximate AMG: repeated damped Jacobi smoothing as inverse apply.
                    # Reuse diagonal inverse if sparsity pattern unchanged.
                    pattern_key = (A_gpu.shape, A_gpu.nnz)
                    if self._amg_diag_inv is None or self._amg_key != pattern_key:
                        diag = A_gpu.diagonal()
                        self._amg_diag_inv = cp.where(diag != 0, 1.0 / diag, 1.0)
                        self._amg_key = pattern_key
                    inv_diag = self._amg_diag_inv
                    base_k = self.amg_smooth_steps
                    k_eff = base_k
                    if self.amg_adaptive and self._last_cg_iters is not None and self.cg_max_iter is not None:
                        frac = self._last_cg_iters / max(1, self.cg_max_iter)
                        # Reduce smoothing if CG already fast
                        if frac < 0.25:
                            k_eff = max(self.amg_min_smooth_steps, base_k - 1)
                        if frac < 0.10:
                            k_eff = max(self.amg_min_smooth_steps, base_k - 2)
                    ω = self.amg_omega
                    def mv(x):
                        # Approx solve A y = x starting y=x * diag^{-1} initial guess for quicker convergence.
                        y = inv_diag * x
                        for _ in range(k_eff - 1):  # already one implicit pre-smooth in init
                            r_loc = x - A_gpu @ y
                            y = y + ω * inv_diag * r_loc
                        return y
                    M = LinearOperator(A_gpu.shape, matvec=mv, dtype=A_gpu.dtype)
                    if self.cg_verbose:
                        print(f"[cupy][cg] amg approx inverse: k={k_eff} (base={base_k}) ω={ω} last_it={self._last_cg_iters}")

                # (3) RHS & warm start
                b_gpu = cp.asarray(b)

                # Dimension sanity check before proceeding
                n_rows = A_gpu.shape[0]
                if b_gpu.ndim > 1:
                    b_gpu = b_gpu.ravel()
                if b_gpu.size != n_rows:
                    # Provide detailed diagnostics and a helpful hint
                    msg = (f"[cupy][cg] Dimension mismatch: A rows={n_rows}, b size={b_gpu.size}. "
                           f"This typically means the load tensor F had unexpected channel count (e.g. 9 instead of 3). "
                           f"Ensure problem.F shape is (3, Nx, Ny, Nz). If it's (9, ...), select only the displacement DOF loads before solving.")
                    raise ValueError(msg)

                cache = self._warm_cache.get(phase, {'x': None, 'b': None, 'θ': None})

                x0 = None
                if self.warm_start and cache['x'] is not None and cache['x'].shape[0] == b_gpu.shape[0]:
                    allow_theta = True
                    allow_rhs = True

                    # (a) θ-based gating (mean density change)
                    if self.warm_strategy in ['theta', 'both'] and θ_current is not None and cache.get('θ') is not None:
                        try:
                            θ_cur_gpu = cp.asarray(θ_current, dtype=cp.float32)
                            θ_prev_gpu = cache['θ']
                            # Ensure shapes match
                            if θ_prev_gpu.shape == θ_cur_gpu.shape:
                                mean_prev = cp.mean(θ_prev_gpu)
                                mean_cur = cp.mean(θ_cur_gpu)
                                abs_mean_diff = float(cp.abs(mean_cur - mean_prev))
                                allow_theta = (abs_mean_diff <= self.warm_theta_tol)
                                if self.cg_verbose:
                                    print(f"[cupy][cg] θ mean_change={abs_mean_diff:.3e} tol={self.warm_theta_tol:.1e} allow={allow_theta}")
                            else:
                                allow_theta = False
                        except Exception as e:
                            allow_theta = False
                            if self.cg_verbose:
                                print(f"[cupy][cg] θ gating error: {e}; skipping warm start")

                    # (b) RHS cosine gating (legacy / mostly relevant if b changes)
                    if self.warm_strategy in ['rhs', 'both'] and cache.get('b') is not None:
                        bn = cp.linalg.norm(b_gpu)
                        bln = cp.linalg.norm(cache['b'])
                        if bn > 0 and bln > 0:
                            cos_sim = float(cp.dot(b_gpu, cache['b']) / (bn * bln))
                            allow_rhs = (cos_sim >= self.warm_similarity_threshold)
                            if self.cg_verbose:
                                print(f"[cupy][cg] b cos={cos_sim:.3f} thr={self.warm_similarity_threshold} allow={allow_rhs}")
                        else:
                            allow_rhs = True  # zero vector; reuse fine
                    
                    # Combine
                    use_warm = False
                    if self.warm_strategy == 'theta':
                        use_warm = allow_theta
                    elif self.warm_strategy == 'rhs':
                        use_warm = allow_rhs
                    else:  # both
                        use_warm = allow_theta and allow_rhs

                    if use_warm:
                        x0 = cache['x']
                        if self.cg_verbose:
                            print(f"[cupy][cg] warm reuse phase={phase} strategy={self.warm_strategy}")
                    else:
                        if self.cg_verbose:
                            print(f"[cupy][cg] warm skip phase={phase} strategy={self.warm_strategy}")

                
                max_iter = self.cg_max_iter
                # Heuristic for max_iter if unspecified: 2 * sqrt(n) (rough) capped at 10k
                # if max_iter is None:
                #     n = b_gpu.shape[0]
                #     max_iter = int(min(10000, max(1000, 2 * int(cp.sqrt(n)))))

                start_time = time.time()
                # Count iterations via callback (cupyx mirrors scipy interface)
                it_counter = {'k': 0}
                def _cb(_):
                    it_counter['k'] += 1
                try:
                    x_gpu, info = cg_spsolve(A_gpu, b_gpu, x0=x0, tol=self.cg_tol, maxiter=max_iter, M=M, callback=_cb)
                except ValueError as ve:
                    # Auto-fallback if block_jacobi caused dimensional issue
                    if self.preconditioner == 'block_jacobi' and 'incompatible dimensions' in str(ve).lower():
                        if self.cg_verbose:
                            print("[cupy][cg] fallback: block_jacobi caused dimension error; retrying with scalar jacobi")
                        diag = A_gpu.diagonal()
                        inv_diag = cp.where(diag != 0, 1.0 / diag, 1.0)
                        def mv(x):
                            return inv_diag * x
                        M_fallback = LinearOperator(A_gpu.shape, matvec=mv, dtype=A_gpu.dtype)
                        it_counter = {'k': 0}
                        def _cb_fb(_):
                            it_counter['k'] += 1
                        x_gpu, info = cg_spsolve(A_gpu, b_gpu, x0=None, tol=self.cg_tol, maxiter=max_iter, M=M_fallback, callback=_cb_fb)
                    else:
                        raise
                cp.cuda.get_current_stream().synchronize()
                elapsed = time.time() - start_time

                if info != 0:
                    # info > 0 -> convergence not achieved within max_iter, info < 0 -> illegal input
                    raise RuntimeError(f"[cupy][cg] convergence failed (info={info}) after {elapsed:.3f}s; consider increasing max_iter or relaxing tol.")

                # Cache warm start
                if self.warm_start:
                    cache['x'] = x_gpu
                    cache['b'] = b_gpu if self.warm_strategy in ['rhs', 'both'] else cache.get('b')
                    if θ_current is not None and self.warm_strategy in ['theta', 'both']:
                        try:
                            cache['θ'] = cp.asarray(θ_current, dtype=cp.float32)
                        except Exception:
                            cache['θ'] = cache.get('θ')  # keep old if failure
                    self._warm_cache[phase] = cache

                # Store last iterations (info==0 -> success) using counter if available
                self._last_cg_iters = it_counter['k'] if it_counter['k'] > 0 else (info if isinstance(info, int) and info > 0 else None)
                if self.cg_verbose:
                    it_disp = self._last_cg_iters if self._last_cg_iters is not None else 'NA'
                    print(f"[cupy][cg] phase={phase} n={b_gpu.shape[0]} time={elapsed:.3f}s tol={self.cg_tol} it={it_disp} warm={'y' if x0 is not None else 'n'} prec={self.preconditioner}")

                # Auto-freeze/unfreeze policy for block_jacobi value updates
                if self.preconditioner == 'block_jacobi' and self.bj_freeze_enabled:
                    st = self._bj_freeze_state
                    # Track theta stability over time
                    if θ_current is not None:
                        try:
                            θ_cur_gpu = cp.asarray(θ_current, dtype=cp.float32)
                            cur_mean = float(cp.mean(θ_cur_gpu).get())
                            if st['prev_mean'] is None:
                                st['prev_mean'] = cur_mean
                            dmean = abs(cur_mean - st['prev_mean'])
                            if dmean <= self.bj_freeze_theta_tol:
                                st['stable_steps'] = int(st.get('stable_steps', 0)) + 1
                            else:
                                st['stable_steps'] = 0
                            st['prev_mean'] = cur_mean
                        except Exception:
                            pass
                    # Freeze when stable enough and not already frozen
                    if (not st.get('frozen', False)) and st.get('stable_steps', 0) >= self.bj_freeze_patience:
                        st['frozen'] = True
                        st['baseline_iters'] = self._last_cg_iters if isinstance(self._last_cg_iters, int) else st.get('baseline_iters')
                        if self.cg_verbose:
                            print(f"[cupy][cg][block_jacobi] auto-freeze: stable_steps={st['stable_steps']} baseline_iters={st['baseline_iters']}")
                    # Unfreeze if iteration count jumps too much
                    if st.get('frozen', False) and st.get('baseline_iters') is not None and isinstance(self._last_cg_iters, int):
                        if self._last_cg_iters > st['baseline_iters'] * self.bj_unfreeze_iter_jump:
                            st['frozen'] = False
                            st['stable_steps'] = 0
                            st['baseline_iters'] = None
                            if self.cg_verbose:
                                print(f"[cupy][cg][block_jacobi] auto-unfreeze: iters jumped {self._last_cg_iters} > {self.bj_unfreeze_iter_jump}× baseline")

                return cp.asnumpy(x_gpu)
                
            return solve_gpu
        # CPU solver (iterative / direct depending on config)
        if self.preconditioner == 'amg':
            def solve_cpu_amg(A, b, phase='forward', θ_current=None):
                # Key by shape + nnz; if nnz unchanged assume pattern stable
                key = (A.shape, A.nnz)
                build = (self._amg_hierarchy is None) or (self._amg_key != key)
                if build:
                    if self.cg_verbose:
                        print(f"[amg] building hierarchy shape={A.shape} nnz={A.nnz}")
                    self._amg_hierarchy = pyamg.smoothed_aggregation_solver(A.tocsr())
                    self._amg_key = key
                # Use acceleration 'cg' with target tolerance (may differ from pyamg's internal default)
                x = self._amg_hierarchy.solve(b, tol=self.cg_tol, accel='cg')
                if self.cg_verbose:
                    print(f"[amg] solve phase={phase} tol={self.cg_tol}")
                return x
            return solve_cpu_amg
        # Default CPU direct solve
        return lambda A, b, phase='forward', θ_current=None: spsolve(A, b, use_umfpack=self.use_umfpack)

# Internal Cell
import copy
import torch

# Cell
class PDESolver:
    """
    A parent class that inherits all PDE solvers.
    """
    def __init__(self,
                 assemble_tensors_when_passed_to_problem:bool=False # Whether the PDE solver methods pre-assembles any tensors or arrays before solving the PDE for a concrete problem.
                ):
        self.assemble_tensors_when_passed_to_problem = assemble_tensors_when_passed_to_problem


    def __call__(self,
                 solution:"dl4to.solution.Solution", # The solution for which the PDE should be solved.
                 p:float=1., # The SIMP exponent when solving the PDE. Should usually be left at its default value of `1.`.
                 binary:bool=False # Whether the densities in the solution should be binarized before solving the PDE.
                ):
        """
        Does the same as the `solve_pde` method. Solves the pde for `solution` and SIMP exponent `p`. Returns three `torch.Tensor` objects: displacements `u`, stresses `σ` and von Mises stresses `σ_vm`.
        """
        return self.solve_pde(solution, p=p, binary=binary)


    def solve_pde(self,
                 solution:"dl4to.solution.Solution", # The solution for which the PDE should be solved.
                 p:float=1., # The SIMP exponent when solving the PDE. Should usually be left at its default value of `1.`.
                 binary:bool=False # Whether the densities in the solution should be binarized before solving the PDE.
                ):
        """
        Solves the pde for `solution` and SIMP exponent `p`. Returns three `torch.Tensor` objects: displacements `u`, stresses `σ` and von Mises stresses `σ_vm`.
        """
        raise NotImplementedError("Must be overridden.")


    def clone(self):
        """
        Returns a `dl4to.pde.PDESolver` object, which is a deepcopy of the PDE solver.
        """
        return copy.deepcopy(self)

# Internal Cell
import torch
import torch.autograd.functional as F

# Cell
class FDMDerivatives():
    @staticmethod
    def du_dx_central(u, h):
        du = torch.zeros_like(u)
        du[:, 1:-1, :,:] = (u[:,  2:, :,:] - u[:, 0:-2, :,:]) / (2 * h[0])
        du[:,  0  , :,:] = (u[:,  1 , :,:] - u[:,  0  , :,:]) / h[0]
        du[:, -1  , :,:] = (u[:, -1 , :,:] - u[:, -2  , :,:]) / h[0]
        return du


    @staticmethod
    def du_dy_central(u, h):
        du = torch.zeros_like(u)
        du[:,:, 1:-1, :] = (u[:,:,  2:, :] - u[:,:, 0:-2, :]) / (2 * h[1])
        du[:,:,  0  , :] = (u[:,:,  1 , :] - u[:,:,  0  , :]) / h[1]
        du[:,:, -1  , :] = (u[:,:, -1 , :] - u[:,:, -2  , :]) / h[1]
        return du


    @staticmethod
    def du_dz_central(u, h):
        du = torch.zeros_like(u)
        du[:,:,:, 1:-1] = (u[:,:,:,  2:] - u[:,:,:, 0:-2]) / (2 * h[2])
        du[:,:,:,  0  ] = (u[:,:,:,  1 ] - u[:,:,:,  0  ]) / h[2]
        du[:,:,:, -1  ] = (u[:,:,:, -1 ] - u[:,:,:, -2  ]) / h[2]
        return du


    @staticmethod
    def du_dx_forward(u, h):
        du = torch.zeros_like(u)
        du[:, 0:-1,:,:] = (u[:,  1:,:,:] - u[:, 0:-1,:,:]) / h[0]
        du[:, -1  ,:,:] = (u[:, -1 ,:,:] - u[:, -2  ,:,:]) / h[0]
        return du


    @staticmethod
    def du_dy_forward(u, h):
        du = torch.zeros_like(u)
        du[:,:, 0:-1,:] = (u[:,:,  1:,:] - u[:,:, 0:-1,:]) / h[1]
        du[:,:, -1  ,:] = (u[:,:, -1 ,:] - u[:,:, -2  ,:]) / h[1]
        return du


    @staticmethod
    def du_dz_forward(u, h):
        du = torch.zeros_like(u)
        du[:,:,:, 0:-1] = (u[:,:,:,  1:] - u[:,:,:, 0:-1]) / h[2]
        du[:,:,:, -1  ] = (u[:,:,:, -1 ] - u[:,:,:, -2  ]) / h[2]
        return du


    @staticmethod
    def du_dx(u, h, use_forward_differences=True):
        assert len(u.shape) == 4
        assert u.shape[1] > 2
        if use_forward_differences:
            return FDMDerivatives.du_dx_forward(u, h)
        return FDMDerivatives.du_dx_central(u, h)


    @staticmethod
    def du_dy(u, h, use_forward_differences=True):
        assert len(u.shape) == 4
        assert u.shape[2] > 2
        if use_forward_differences:
            return FDMDerivatives.du_dy_forward(u, h)
        return FDMDerivatives.du_dy_central(u, h)


    @staticmethod
    def du_dz(u, h, use_forward_differences=True):
        assert len(u.shape) == 4
        assert u.shape[3] > 2
        if use_forward_differences:
            return FDMDerivatives.du_dz_forward(u, h)
        return FDMDerivatives.du_dz_central(u, h)

# Cell
class FDMAdjointDerivatives():
    @staticmethod
    def du_dx_adj_for_a_sufficiently_large_number_of_voxels(ε, h):
        u = torch.zeros_like(ε)
        u[:,   0,:,:] = -(2 * ε[:,   0,:,:] + ε[:,   1,:,:]) / (2 * h[0])
        u[:,   1,:,:] =  (2 * ε[:,   0,:,:] - ε[:,   2,:,:]) / (2 * h[0])
        u[:,2:-2,:,:] =  (    ε[:,1:-3,:,:] - ε[:,3:-1,:,:]) / (2 * h[0])
        u[:,  -2,:,:] = -(2 * ε[:,  -1,:,:] - ε[:,  -3,:,:]) / (2 * h[0])
        u[:,  -1,:,:] =  (2 * ε[:,  -1,:,:] + ε[:,  -2,:,:]) / (2 * h[0])
        return u


    @staticmethod
    def du_dy_adj_for_a_sufficiently_large_number_of_voxels(ε, h):
        u = torch.zeros_like(ε)
        u[:,:,   0,:] = -(2 * ε[:,:,   0,:] + ε[:,:,   1,:]) / (2 * h[1])
        u[:,:,   1,:] =  (2 * ε[:,:,   0,:] - ε[:,:,   2,:]) / (2 * h[1])
        u[:,:,2:-2,:] =  (    ε[:,:,1:-3,:] - ε[:,:,3:-1,:]) / (2 * h[1])
        u[:,:,  -2,:] = -(2 * ε[:,:,  -1,:] - ε[:,:,  -3,:]) / (2 * h[1])
        u[:,:,  -1,:] =  (2 * ε[:,:,  -1,:] + ε[:,:,  -2,:]) / (2 * h[1])
        return u


    @staticmethod
    def du_dz_adj_for_a_sufficiently_large_number_of_voxels(ε, h):
        u = torch.zeros_like(ε)
        u[:,:,:,   0] = -(2 * ε[:,:,:,   0] + ε[:,:,:,   1]) / (2 * h[2])
        u[:,:,:,   1] =  (2 * ε[:,:,:,   0] - ε[:,:,:,   2]) / (2 * h[2])
        u[:,:,:,2:-2] =  (    ε[:,:,:,1:-3] - ε[:,:,:,3:-1]) / (2 * h[2])
        u[:,:,:,  -2] = -(2 * ε[:,:,:,  -1] - ε[:,:,:,  -3]) / (2 * h[2])
        u[:,:,:,  -1] =  (2 * ε[:,:,:,  -1] + ε[:,:,:,  -2]) / (2 * h[2])
        return u


    @staticmethod
    def du_dx_adj_for_a_sufficiently_small_number_of_voxels(ε, h):
        u = torch.zeros_like(ε)

        if u.shape[1] == 2:
            u[:, 0,:,:] = -(ε[:, 0,:,:] +  ε[:, 1,:,:]) / h[0]
            u[:, 1,:,:] = - u[:, 0,:,:]

        if u.shape[1] == 3:
            u[:,0,:,:] = -(2 * ε[:,0,:,:] + ε[:,1,:,:]) / (2 * h[0])
            u[:,1,:,:] =  (    ε[:,0,:,:] - ε[:,2,:,:]) /  h[0]
            u[:,2,:,:] =  (2 * ε[:,2,:,:] + ε[:,1,:,:]) / (2 * h[0])

        return u


    @staticmethod
    def du_dy_adj_for_a_sufficiently_small_number_of_voxels(ε, h):
        u = torch.zeros_like(ε)

        if u.shape[2] == 2:
            u[:,:, 0,:] = -(ε[:,:, 0,:] +  ε[:,:, 1,:]) / h[1]
            u[:,:, 1,:] = - u[:,:, 0,:]

        if u.shape[2] == 3:
            u[:,:,0,:] = -(2 * ε[:,:,0,:] + ε[:,:,1,:]) / (2 * h[1])
            u[:,:,1,:] =  (    ε[:,:,0,:] - ε[:,:,2,:]) /  h[1]
            u[:,:,2,:] =  (2 * ε[:,:,2,:] + ε[:,:,1,:]) / (2 * h[1])

        return u


    @staticmethod
    def du_dz_adj_for_a_sufficiently_small_number_of_voxels(ε, h):
        u = torch.zeros_like(ε)

        if u.shape[3] == 2:
            u[:,:,:, 0] = -(ε[:,:,:, 0] +  ε[:,:,:, 1]) / h[2]
            u[:,:,:, 1] = - u[:,:,:, 0]

        if u.shape[3] == 3:
            u[:,:,:,0] = -(2 * ε[:,:,:,0] + ε[:,:,:,1]) / (2 * h[2])
            u[:,:,:,1] =  (    ε[:,:,:,0] - ε[:,:,:,2]) /  h[2]
            u[:,:,:,2] =  (2 * ε[:,:,:,2] + ε[:,:,:,1]) / (2 * h[2])

        return u


    @staticmethod
    def du_dx_adj_forward(ε, h):
        u = torch.zeros_like(ε)
        u[:,   0   ,:,:] =  (                 - ε[:,      0,:,:]) / h[0]
        u[:,   1:-2,:,:] =  (ε[:,   0:-3,:,:] - ε[:,   1:-2,:,:]) / h[0]
        u[:,     -2,:,:] =  (ε[:,  -3,:,:] - ε[:,  -2,:,:] - ε[:,  -1,:,:]) / h[0]
        u[:,     -1,:,:] =  (ε[:,     -2,:,:] + ε[:,     -1,:,:]) / h[0]
        return u


    @staticmethod
    def du_dy_adj_forward(ε, h):
        u = torch.zeros_like(ε)
        u[:,:,   0   ,:] =  (                 - ε[:,:,      0,:]) / h[1]
        u[:,:,   1:-2,:] =  (ε[:,:,   0:-3,:] - ε[:,:,   1:-2,:]) / h[1]
        u[:,:,     -2,:] =  (ε[:,:,  -3,:] - ε[:,:,  -2,:] - ε[:,:,  -1,:]) / h[1]
        u[:,:,     -1,:] =  (ε[:,:,     -2,:] + ε[:,:,     -1,:]) / h[1]
        return u


    @staticmethod
    def du_dz_adj_forward(ε, h):
        u = torch.zeros_like(ε)
        u[:,:,:,   0   ] =  (                 - ε[:,:,:,      0]) / h[2]
        u[:,:,:,   1:-2] =  (ε[:,:,:,   0:-3] - ε[:,:,:,   1:-2]) / h[2]
        u[:,:,:,     -2] =  (ε[:,:,:,  -3] - ε[:,:,:,  -2] - ε[:,:,:,  -1]) / h[2]
        u[:,:,:,     -1] =  (ε[:,:,:,     -2] + ε[:,:,:,     -1]) / h[2]
        return u


    @staticmethod
    def du_dx_adj(ε, h, use_forward_differences=True):
        assert len(ε.shape) == 4
        if use_forward_differences:
            return FDMAdjointDerivatives.du_dx_adj_forward(ε, h)


        if ε.shape[1] > 3:
            return FDMAdjointDerivatives.du_dx_adj_for_a_sufficiently_large_number_of_voxels(ε, h)
        return FDMAdjointDerivatives.du_dx_adj_for_a_sufficiently_small_number_of_voxels(ε, h)


    @staticmethod
    def du_dy_adj(ε, h, use_forward_differences=True):
        assert len(ε.shape) == 4
        if use_forward_differences:
            return FDMAdjointDerivatives.du_dy_adj_forward(ε, h)


        if ε.shape[2] > 3:
            return FDMAdjointDerivatives.du_dy_adj_for_a_sufficiently_large_number_of_voxels(ε, h)
        return FDMAdjointDerivatives.du_dy_adj_for_a_sufficiently_small_number_of_voxels(ε, h)


    @staticmethod
    def du_dz_adj(ε, h, use_forward_differences=True):
        assert len(ε.shape) == 4
        if use_forward_differences:
            return FDMAdjointDerivatives.du_dz_adj_forward(ε, h)


        if ε.shape[3] > 3:
            return FDMAdjointDerivatives.du_dz_adj_for_a_sufficiently_large_number_of_voxels(ε, h)
        return FDMAdjointDerivatives.du_dz_adj_for_a_sufficiently_small_number_of_voxels(ε, h)

# Internal Cell
import torch
import numpy as np
from scipy.sparse import csc_matrix, hstack
import time

# Cell
class FDMAssembly():
    """
    This class contains methods that are used for the assembly of the FDM stiffness matrix.
    """

    @staticmethod
    def apply_dirichlet_zero_rows_to_operator(operator, Ω_dirichlet):
        """
        Returns a version of `operator` that fulfills the dirichlet conditions in the output.

        Returns
        -------
        torch.Tensor
        """
        def operator_with_dirichlet_rows_zero(x):
            assert len(Ω_dirichlet.shape) == len(x.shape) == 4
            y = operator(x)
            y[Ω_dirichlet] = 0
            return y

        return operator_with_dirichlet_rows_zero


    @staticmethod
    def apply_dirichlet_zero_columns_to_operator(operator, Ω_dirichlet):
        """
        Returns a version of `operator` that fulfills the dirichlet conditions in the input.

        Returns
        -------
        torch.Tensor
        """
        def operator_with_dirichlet_columns_zero(x):
            assert len(Ω_dirichlet.shape) == len(x.shape) == 4
            x = x.clone()
            x[Ω_dirichlet] = 0
            y = operator(x)
            return y

        return operator_with_dirichlet_columns_zero


    @staticmethod
    def _get_graph(operator, shape, channels_in, filter_shape):
        operator_graph = []

        for i in range(filter_shape[0]):
            for j in range(filter_shape[1]):
                for k in range(filter_shape[2]):
                    for c in range(channels_in):
                        x = torch.zeros(channels_in, *shape)
                        x[c, i::filter_shape[0], j::filter_shape[1], k::filter_shape[2]] = 1
                        operator_graph.append((x.numpy(), operator(x).numpy()))

        return operator_graph


    @staticmethod
    def _get_nbh_coordinates(pos_in_nbhs, channels_in, channels_out):
        assert pos_in_nbhs.shape[1:] == (4,)
        channels_prod = channels_in * channels_out
        nbh_coordinates = -2 * np.ones([pos_in_nbhs.shape[0], channels_prod*channels_out, 4])
        centroids = np.zeros([pos_in_nbhs.shape[0], channels_prod*channels_out, 4])

        if pos_in_nbhs.shape[0] > 0:
            centroids[:] = pos_in_nbhs[0]

        for c in range(channels_out):
            nbh_coordinates[:, channels_prod*c:channels_prod*(c+1), 0] = c

        for i in range(-1, 2):
            for j in range(-1, 2):
                for k in range(-1, 2):
                    if [i,j,k].count(0) >= 2:
                        rhs = pos_in_nbhs[:, 1:] + np.array([i, j, k])
                        t = channels_out * (i + 1) + channels_in * (j + 1) + (k + 1)
                        nbh_coordinates[:, t::channels_prod, 1:] = rhs.reshape(pos_in_nbhs.shape[0], 1, 3)
                        centroids[:, t::channels_prod, 1:] = pos_in_nbhs[:, 1:].reshape(pos_in_nbhs.shape[0], 1, 3)

        assert nbh_coordinates.shape[1:] == (channels_prod*channels_out, 4)
        return nbh_coordinates.reshape(-1, 4), centroids.reshape(-1, 4)


    @staticmethod
    def _remove_out_of_bounds_rows(nbh_coordinates, centroids, shape):
        mask0 = np.all(nbh_coordinates >=0, axis=1, keepdims=True).flatten()
        mask1 = nbh_coordinates[:,1] < shape[0]
        mask2 = nbh_coordinates[:,2] < shape[1]
        mask3 = nbh_coordinates[:,3] < shape[2]

        mask = mask0 & mask1 & mask2 & mask3
        return nbh_coordinates[mask].astype(int), centroids[mask].astype(int)


    @staticmethod
    def _get_1d_coordinates(positions, shape):
        assert positions.shape[1:] == (4,)
        coords_1d = positions[:,3] + shape[2]*positions[:,2] + shape[1] * shape[2] * positions[:,1] +  shape[0] * shape[1] * shape[2] * positions[:,0]
        return coords_1d.astype(int)


    @staticmethod
    def assemble_operator(operator, shape, channels_in=3, channels_out=9, filter_shape=3, Ω_dirichlet=None, column_wise=True):
        """
        Returns a sparse assembly of `operator`.

        Returns
        -------
        scipy.sparse.csc_matrix
        """
        if type(filter_shape) is int:
            filter_shape = [filter_shape, filter_shape, filter_shape]

        if Ω_dirichlet is not None:
            if column_wise:
                operator = FDMAssembly.apply_dirichlet_zero_columns_to_operator(operator, Ω_dirichlet)
            else:
                operator = FDMAssembly.apply_dirichlet_zero_rows_to_operator(operator, Ω_dirichlet)

        op_graph = FDMAssembly._get_graph(operator, shape, channels_in, filter_shape)
        col_indices = []
        row_indices = []
        values = []

        for x, y in op_graph:
            pos_in_nbhs = np.where(x)
            pos_in_nbhs = np.stack(pos_in_nbhs).transpose()

            nbh_3d, centroids = FDMAssembly._get_nbh_coordinates(pos_in_nbhs, channels_in, channels_out)
            nbh_3d, centroids = FDMAssembly._remove_out_of_bounds_rows(nbh_3d, centroids, shape)

            col_idx = FDMAssembly._get_1d_coordinates(centroids, shape)
            row_idx = FDMAssembly._get_1d_coordinates(nbh_3d, shape)

            col_indices.extend(col_idx)
            row_indices.extend(row_idx)

            vals = np.take(y.flatten(), row_idx, axis=0)
            values.extend(vals)

        return csc_matrix((values, (row_indices, col_indices)), shape=(channels_out*np.prod(shape), channels_in*np.prod(shape)))

# Internal Cell
import torch
import warnings
import numpy as np
from scipy.sparse import diags, csc_matrix


# from .pde import SparseLinearSolver, PDESolver, FDMDerivatives, FDMAdjointDerivatives, FDMAssembly
from .utils import get_σ_vm

# Cell
class UnpaddedFDM(PDESolver):
    """
    A PDE solver for linear elasticity that uses the finite differences method (FDM) with padding.
    """
    def __init__(self, θ_min:float=1e-6, # The minimal value in the stiffness matrix. For numerical reasons we can not allow 0s, since they may lead to singular matrices.
                 use_forward_differences:bool=True, # Whether to use forward differences or central differences.
                 assemble_tensors_when_passed_to_problem:bool=True, # Whether the PDE solver methods pre-assembles any tensors or arrays before solving the PDE for a concrete problem.
                 ):
        self._θ_min = θ_min
        # Use iterative solver (factorize=False) to allow θ-based warm-start gating & GPU path
        self._linear_solver = SparseLinearSolver(
            use_umfpack=True,
            factorize=False,
            use_cupy=True,
            warm_strategy='theta',
            warm_theta_tol=1e-2
        )
        self.use_forward_differences = use_forward_differences
        self.assemble_tensors_when_passed_to_problem = assemble_tensors_when_passed_to_problem
        self.assembled_tensors = False
        super().__init__(assemble_tensors_when_passed_to_problem)


    @property
    def problem(self):
        return self._problem


    @property
    def shape(self):
        return self.problem.shape


    @property
    def Ω_dirichlet(self):
        return self.problem.Ω_dirichlet


    @property
    def θ_min(self):
        return self._θ_min


    @property
    def b(self):
        return self._b


    @property
    def h(self):
        return self.problem.h


    @property
    def linear_solver(self):
        return self._linear_solver


    def assemble_tensors(self,
                         problem:"dl4to.problem.Problem" # The problem for which the tensors should be assembled.
                        ):
        """
        Assembles all FDM tensors from the problem object that can be pre-built without knowledge of the density distribution `θ`. This may take some time but makes future PDE evaluations for this problem much faster.
        """
        self._problem = problem.clone()
        GJ = lambda u: self._G(self._J(u))
        self._Ω_dirichlet_diags = diags(self.Ω_dirichlet.flatten().int().numpy())
        self._Jt_mat = FDMAssembly.assemble_operator(
            operator=self._J, shape=self.shape,
            Ω_dirichlet=self.Ω_dirichlet,
            filter_shape=3).transpose()
        self._GJ_mat = FDMAssembly.assemble_operator(
            operator=GJ, shape=self.shape, Ω_dirichlet=self.Ω_dirichlet, filter_shape=3)
        self._b = self._get_b()
        self.assembled_tensors = True


    def _get_θ_from_solution(self, solution, binary=False, clone=False):
        if clone:
            θ = solution.get_θ(binary).clone()
        else:
            θ = solution.get_θ(binary)
        return θ


    def _J(self, u, dirichlet=False):
        J = lambda u: torch.cat([
            FDMDerivatives.du_dx(u, self.h, self.use_forward_differences),
            FDMDerivatives.du_dy(u, self.h, self.use_forward_differences),
            FDMDerivatives.du_dz(u, self.h, self.use_forward_differences)
        ], dim=0)

        if dirichlet:
            return FDMAssembly.apply_dirichlet_zero_columns_to_operator(J, self.Ω_dirichlet)(u)
        return J(u)


    def _J_adj(self, σ, dirichlet=False):
        Jt = lambda σ: FDMAdjointDerivatives.du_dx_adj(σ[:3],  self.h, self.use_forward_differences) + \
                       FDMAdjointDerivatives.du_dy_adj(σ[3:6], self.h, self.use_forward_differences) + \
                       FDMAdjointDerivatives.du_dz_adj(σ[6:],  self.h, self.use_forward_differences)

        if dirichlet:
            return FDMAssembly.apply_dirichlet_zero_rows_to_operator(Jt, self.Ω_dirichlet)(σ)
        return Jt(σ)


    def _get_G(self):
        ν = self.problem.ν

        G = torch.tensor([
            [1-ν,  0-0,  0-0,    0-0,  ν-0,  0-0,    0-0,  0-0,  ν-0],
            [0-0, .5-ν,  0-0,   .5-ν,  0-0,  0-0,    0-0,  0-0,  0-0],
            [0-0,  0-0, .5-ν,    0-0,  0-0,  0-0,   .5-ν,  0-0,  0-0],

            [0-0, .5-ν,  0-0,   .5-ν,  0-0,  0-0,    0-0,  0-0,  0-0],
            [ν-0,  0-0,  0-0,    0-0,  1-ν,  0-0,    0-0,  0-0,  ν-0],
            [0-0,  0-0,  0-0,    0-0,  0-0, .5-ν,    0-0, .5-ν,  0-0],

            [0-0,  0-0, .5-ν,    0-0,  0-0,  0-0,   .5-ν,  0-0,  0-0],
            [0-0,  0-0,  0-0,    0-0,  0-0, .5-ν,    0-0, .5-ν,  0-0],
            [ν-0,  0-0,  0-0,    0-0,  ν-0,  0-0,    0-0,  0-0,  1-ν]
        ], dtype=self.problem.dtype)

        G = G.to(self.problem.device)
        return G / ((1 + ν) * (1 - 2 * ν))


    def _G(self, ε):
        ε = ε.type(self.problem.dtype)
        return torch.einsum('ij, jlmn -> ilmn', self._get_G(), ε)


    def _G_adj(self, σ):
        σ = σ.type(self.problem.dtype)
        return torch.einsum('ij, jlmn -> ilmn', self._get_G().t(), σ)


    def _GJ(self, u, dirichlet=False):
        apply_GJ = lambda u: self._G(self._J(u))

        if dirichlet:
            return FDMAssembly.apply_dirichlet_zero_columns_to_operator(apply_GJ, self.Ω_dirichlet)(u)
        return apply_GJ(u)


    def _GJ_adj(self, σ, dirichlet=False):
        apply_GJ_adj = lambda σ: self._J_adj(self._G_adj(σ))

        if dirichlet:
            return FDMAssembly.apply_dirichlet_zero_rows_to_operator(apply_GJ_adj, self.Ω_dirichlet)(σ)
        return apply_GJ_adj(σ)


    def _apply_θp(self, σ, θ, p=1., normalize=True):
        E = 1. if normalize else self.problem.E
        E_min = E * self.θ_min
        θ_ = E_min + θ**p * (E - E_min)
        return θ_ * σ


    def _assemble_θ(self, θ, p=1.):
        E = 1.
        E_min = E * self.θ_min
        θ_ = E_min + (θ**p).flatten().repeat(9).detach().numpy() * (E - E_min)
        return diags(θ_)


    def _A(self, u, θ, dirichlet=True, p=1.):
        u = u.view(3, θ.shape[-3], θ.shape[-2], θ.shape[-1])
        y = self._GJ(u, dirichlet)
        y = self._apply_θp(y, θ, p)
        y = self._J_adj(y, dirichlet)

        if dirichlet:
            y[self.Ω_dirichlet] = u.clone()[self.Ω_dirichlet]
        return y


    def _A_adj(self, y, θ, dirichlet=True, p=1.):
        y = y.view(3, θ.shape[-3], θ.shape[-2], θ.shape[-1])
        u = self._J(y, dirichlet)
        u = self._apply_θp(u, θ, p)
        u = self._GJ_adj(u, dirichlet)

        if dirichlet:
            u[self.Ω_dirichlet] = y.clone()[self.Ω_dirichlet]
        return u


    def _assemble_A(self, θ, p=1.):
        θ_mat = self._assemble_θ(θ, p)
        A = self._Jt_mat.dot(θ_mat.dot(self._GJ_mat)) + self._Ω_dirichlet_diags
        return csc_matrix(A)


    def _get_b(self):
        b = self.problem.F
        b[self.Ω_dirichlet] = 0
        b /= self.problem.E
        return b


    def _get_u(self, solution, p=1., binary=False):
        if binary and (solution.u_binary is not None):
            return solution.u_binary

        if (not binary) and (solution.u is not None):
            return solution.u

        if not self.assembled_tensors:
            self.assemble_tensors(solution.problem)

        θ = self._get_θ_from_solution(solution, binary=binary, clone=True)
        θ = θ.clamp(self.θ_min, 1)
        A_op = lambda u, θ: self._A(u, θ, p=p)
        A_mat = self._assemble_A(θ.cpu(), p)
        u = self._linear_solver(θ.cpu(), A_op, self.b.flatten(), A_mat)
        u = u.view(3, θ.shape[-3], θ.shape[-2], θ.shape[-1]).to(θ.device)

        if binary:
            solution.u_binary = u.clone()
        else:
            solution.u = u.clone()

        return u


    def _get_σ(self, solution, p=1., u=None, binary=False):
        if u is None:
            u = self._get_u(solution, p=p, binary=binary)

        θ = self._get_θ_from_solution(solution, binary=binary, clone=False)
        ε = self._J(u)
        σ = self._G(ε)
        σ = self._apply_θp(σ, θ, p=1., normalize=False)
        return σ


    def _stack_if_tensor_else_return_none(self, list):
        if any(type(entry) is not torch.Tensor for entry in list):
            return None
        return torch.stack(list)


    def solve_pde(self,
                 solution:"dl4to.solution.Solution", # The solution for which the PDE should be solved.
                 p:float=1., # The SIMP exponent when solving the PDE. Should usually be left at its default value of `1.`.
                 binary:bool=False # Whether the densities in the solution should be binarized before solving the PDE.
                ):
        """
        Solves the pde for `solution` and SIMP exponent `p`. Returns three `torch.Tensor` objects: displacements `u`, stresses `σ` and von Mises stresses `σ_vm`.
        """
        u = self._get_u(solution, p=p, binary=binary)
        σ = self._get_σ(solution, p=p, u=u, binary=binary)
        σ_vm = get_σ_vm(σ)
        return u, σ, σ_vm

# Cell
class FDM(UnpaddedFDM):
    """
    A PDE solver for linear elasticity that uses the finite differences method (FDM) with padding.
    """
    def __init__(self, θ_min:float=1e-6, # The minimal value in the stiffness matrix. For numerical reasons we can not allow 0s, since they may lead to singular matrices.
                 use_forward_differences:bool=True, # Whether to use forward differences or central differences.
                 assemble_tensors_when_passed_to_problem:bool=True, # Whether the PDE solver methods pre-assembles any tensors or arrays before solving the PDE for a concrete problem.
                 padding_depth:int=0 # The depth of the padding surrounding the design space. In some cases, it is recommended to increase the padding depth to 2 to improve results but also increase running time.
                ):
        self.padding_depth = padding_depth
        super().__init__(
            θ_min=θ_min,
            use_forward_differences=use_forward_differences,
            assemble_tensors_when_passed_to_problem=assemble_tensors_when_passed_to_problem
        )


    @property
    def shape(self):
        return self.Ω_dirichlet.shape[-3:]


    @property
    def Ω_dirichlet(self):
        return self._get_padded_tensor(self.problem.Ω_dirichlet)


    def _get_padded_tensor(self, tensor):
        p_d = int(self.padding_depth)
        if p_d == 0:
            return tensor

        shape = tensor.shape
        assert len(shape) == 4
        padded_tensor = torch.zeros(
            shape[0], shape[1]+2*p_d, shape[2]+2*p_d, shape[3]+2*p_d, dtype=tensor.dtype
        )
        padded_tensor[:, p_d:-p_d, p_d:-p_d, p_d:-p_d] = tensor
        return padded_tensor


    def _remove_padding(self, tensor):
        p_d = int(self.padding_depth)
        if p_d == 0:
            return tensor

        shape = tensor.shape
        assert len(shape) == 4
        return tensor[:, p_d:-p_d, p_d:-p_d, p_d:-p_d]


    def _get_θ_from_solution(self, solution, binary=False, clone=False):
        θ = super()._get_θ_from_solution(solution, binary=binary, clone=clone)
        return self._get_padded_tensor(θ)


    def _A(self, u, θ, dirichlet=True, p=1.):
        if θ.shape[-3:] == self.shape[-3:]:
            return super()._A(u=u, θ=θ, dirichlet=dirichlet, p=p)
        θ_padded = self._get_padded_tensor(θ)
        assert θ_padded.shape[-3:] == self.shape[-3:]
        return super()._A(u=u, θ=θ_padded, dirichlet=dirichlet, p=p)


    def _A_adj(self, y, θ, dirichlet=True, p=1.):
        if θ.shape[-3:] == self.shape[-3:]:
            return super()._A_adj(y=y, θ=θ, dirichlet=dirichlet, p=p)
        θ_padded = self._get_padded_tensor(θ)
        assert θ_padded.shape[-3:] == self.shape[-3:]
        return super()._A_adj(y=y, θ=θ_padded, dirichlet=dirichlet, p=p)


    def _get_b(self):
        b = self.problem.F
        b = self._get_padded_tensor(b)
        b[self.Ω_dirichlet] = 0
        b /= self.problem.E
        return b


    def _get_u(self, solution, p=1., binary=False, get_padded=False):
        u = super()._get_u(solution, p=p, binary=binary)
        if get_padded:
            return u
        return self._remove_padding(u)


    def _get_σ(self, solution, p=1., u=None, binary=False, get_padded=False):
        if u is None:
            u = self._get_u(solution, p=p, binary=binary, get_padded=True)
        σ = super()._get_σ(solution, p=p, u=u, binary=binary)
        if get_padded:
            return σ
        return self._remove_padding(σ)


    def solve_pde(self,
                 solution:"dl4to.solution.Solution", # The solution for which the PDE should be solved.
                 p:float=1., # The SIMP exponent when solving the PDE. Should usually be left at its default value of `1.`.
                 binary:bool=False, # Whether the densities in the solution should be binarized before solving the PDE.
                 get_padded:bool=False # Whether the density should be padded before the PDE is solved. Takes a bit longer to solve, but is more accurate.
                ):
        """
        Solves the pde for `solution` and SIMP exponent `p`. Returns three `torch.Tensor` objects: displacements `u`, stresses `σ` and von Mises stresses `σ_vm`.
        """
        u = self._get_u(solution, p=p, binary=binary, get_padded=True)
        σ = self._get_σ(solution, p=p, u=u, binary=binary, get_padded=True)
        σ_vm = get_σ_vm(σ)
        if get_padded:
            return u, σ, σ_vm
        return self._remove_padding(u), self._remove_padding(σ), self._remove_padding(σ_vm)